### ISSUE TITLE
Unable to launch on M1 Mac

### ISSUE THREAD

**Issue by frantzmiccoli** [DropbaseHQ/dropbase#15]
I am encountering an issue after cloning the project (`main`branch) and trying to launch it.

It doesn't look like an architecture issue.

Mac OS 12.7.4
Docker Desktop 4.26.0

```
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 404, in main
    run(
  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/project/server/main.py", line 8, in <module>
    from server import routers
  File "/project/server/routers/__init__.py", line 1, in <module>
    from server.routers.app import router as app_router
  File "/project/server/routers/app.py", line 4, in <module>
    from server.constants import DEFAULT_RESPONSES
  File "/project/server/constants.py", line 3, in <module>
    from server.config import server_envs
  File "/project/server/config.py", line 9, in <module>
    server_envs = load_toml("server.toml")
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/server/config.py", line 5, in load_toml
    with open(file_name) as file:
         ^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'server.toml'
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 404, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/project/server/main.py", line 8, in <module>
    from server import routers
  File "/project/server/routers/__init__.py", line 1, in <module>
    from server.routers.app import router as app_router
  File "/project/server/routers/app.py", line 4, in <module>
    from server.constants import DEFAULT_RESPONSES
  File "/project/server/constants.py", line 3, in <module>
    from server.config import server_envs
  File "/project/server/config.py", line 9, in <module>
    server_envs = load_toml("server.toml")
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/server/config.py", line 5, in load_toml
    with open(file_name) as file:
         ^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'server.toml'
```

**Comment by azhakhan** [comment]
hey @frantzmiccoli,

thanks for submitting the issue.

when you run start.sh for the first time, it should have created server.toml and worker.toml files in the root directory:
<img width="347" alt="image" src="https://github.com/user-attachments/assets/2213b0b5-eeb6-418f-b732-1803cf7d272d">

could you confirm you have those files in your file system?

**Comment by frantzmiccoli** [comment]
Sorry I didn't see the notification.

Yes, I do have those files that are created.

**Comment by azhakhan** [comment]
hey @frantzmiccoli ,

we've launched a new version of Dropbase that requires fewer setup steps. can you pull the new version try again?

**Comment by frantzmiccoli** [comment]
Hey,

I have tried again. Recloning the repo. Different error.

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/host_mnt/Users/redacteduser/workspaces/python/dropbase-test/server.toml" to rootfs at "/project/server.toml": mount /host_mnt/Users/redacteduser/workspaces/python/dropbase-test/server.toml:/project/server.toml (via /proc/self/fd/9), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

Could it be a cache within docker?

**Comment by azhakhan** [comment]
let's try using absolute paths in docker-compose.

can you update docker-compose.yml to this and try starting it again?

```
services:
  dropbase-client:
    image: dropbase/client:0.6.7
    ports:
      - "3030:80"
    depends_on:
      - dropbase-lsp
  dropbase-server:
    image: dropbase/server:0.6.7
    volumes:
      - ${HOST_PATH}/workspace:/project/workspace
      - ${HOST_PATH}/files:/project/files
      - ${HOST_PATH}/server.toml:/project/server.toml
      - ${HOST_PATH}/pyproject.py.toml:/project/pyproject.py.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - HOST_PATH=${HOST_PATH}
  dropbase-lsp:
    image: dropbase/lsp:0.1.1
    volumes:
      - ${HOST_PATH}/workspace:/project/workspace
      - ${HOST_PATH}/files:/project/files
      - ${HOST_PATH}/ruff.toml:/project/ruff.toml
      - /var/run/docker.sock:/var/run/docker.sock
      # Attach custom volumes here
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "9095:9095"
  redis:
    image: redis
    ports:
      - 6379:6379
```

**Comment by frantzmiccoli** [comment]
Hello,

I have tried, and now it starts, yet doesn't work.

When I go to http://127.0.0.1:3030/ I see a message: "Please connect to a worker to view and create apps." in the interface that appears. I don't see logs that resembles errors in the output of the start.sh script (that seems to get the apps logs).

Thanks

**Comment by azhakhan** [comment]
hey @frantzmiccoli,

sorry about that. can we schedule a zoom call and try troubleshooting it together? please contact us at support@dropbase.io.

thank you!
